### ISSUE TITLE
why do not find the attribute ‘create_user_embedding’

### ISSUE THREAD

**Issue by AlexNLP** [MrYansong/CCasGNN#1]
When I reprocedured your codes, I faced this problem!
---
Traceback (most recent call last):
  File "/home/zw/data/CCasGNN-main/main.py", line 30, in <module>
    main()
  File "/home/zw/data/CCasGNN-main/main.py", line 24, in main
    model.fit()
  File "/home/zw/data/CCasGNN-main/CCasGNN.py", line 194, in fit
    train_data_x, train_data_y = self.create_forward_data(self.train_batches)
  File "/home/zw/data/CCasGNN-main/CCasGNN.py", line 184, in create_forward_data
    input_data, target = self.create_input_data(each_data)
  File "/home/zw/data/CCasGNN-main/CCasGNN.py", line 170, in create_input_data
    user_embedding = self.create_user_embedding(data)
  File "/usr/local/anaconda3/envs/zw/lib/python3.6/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'CCasGNN_Trainer' object has no attribute 'create_user_embedding'
---

and  I found this code haven't  the attribute ‘create_user_embedding’, could you tell me how to resolve this problem?
![image](https://user-images.githubusercontent.com/59248970/166399896-ded598d7-27e2-4b99-bb7e-54b5804f7a64.png)

**Comment by MrYansong** [comment]
You can comment out this line, because there’s a function to generate the embedding.

**Comment by AlexNLP** [comment]
> You can comment out this line, because there’s a function to generate the embedding.

you have tackled out my problem, Many thanks for you!
